### ISSUE TITLE
Question about the dataset and the split file

### ISSUE THREAD

**Issue by JoyHighmore** [SimonGiebenhain/AIR-Nets#1]
Hi! 

I've trying to run your code. And I am a bit confused about how to deal with the dataset from occupancy networks. As I know, the dataset downloaded from the Onet has already been processed and the split file is not npz but lst file. So you don't use the exactly the same dataset as Onet?

Best,
J

**Comment by SimonGiebenhain** [comment]
Hi,

since we started out with the data from IF-Nets, we used their split file as well. The file can be found here: https://github.com/jchibane/if-net/tree/master/shapenet

Sorry for the inconvenience.

Kind regards,
Simon
